### ISSUE TITLE
Add profile photo to the Rank list

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityMetrics#13]
see: https://github.com/DNNCommunity/Dnn.CommunityMetrics/issues/3

**Comment by david-poindexter** [comment]
Closing as this is already documented in issue #3 - thanks!

**Comment by Timo-Breumelhof** [comment]
@david-poindexter Right I thought it was another repo, but I was wrong :-)

**Comment by david-poindexter** [comment]
Hehe - I was wondering.  LOL - thank you - best to make sure nonetheless so at least this caused that validation to happen.  :)
