### ISSUE TITLE
View count = Visitor count

### ISSUE THREAD

**Issue by X3Technology** [DNNCommunity/Dnn.CommunityMetrics#2]
View count = Visitor count

**Comment by X3Technology** [comment]
Resolved

**Comment by david-poindexter** [comment]
How was this resolved?  Was there a pull request?

**Comment by X3Technology** [comment]
still learning...

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by WillStrohl** [comment]
@mathisjay Yeah, completely understand.  If you do updates using the standard Gitflow, then we can all see, help, review, and test updates better.   Basically, it helps us all be more useful to each other.  😄 

If you want for me to walk you though this, I'd be happy to have a meeting with you online.

**Comment by david-poindexter** [comment]
Closing this issue due to lack of clarity on the issue and resolution.  If anyone has further insight, please reply and we can re-open this issue.  Thanks.
