### ISSUE TITLE
Add in User Profile Avatar to Dashboard Listing

### ISSUE THREAD

**Issue by CBPSC** [DNNCommunity/Dnn.CommunityMetrics#3]
It would "humanize" and make the dashboard more visual to add in the user's avatar in the dashboard listing and pop-up.

**Comment by david-poindexter** [comment]
I am finally getting a bit of time to look into this.  Here is what I propose and will try to get this into the next release.

![image](https://github.com/DNNCommunity/Dnn.CommunityMetrics/assets/4568451/7d4af12c-cbef-40e2-8d3a-522bcd5f450e)
