### ISSUE TITLE
Activity is not being tracked for some users for some unknown reason

### ISSUE THREAD

**Issue by WillStrohl** [DNNCommunity/Dnn.CommunityMetrics#30]
As of right now, it appears that the only way one gets credit in the community leaderboard from GitHub activity is if they contribute in some way directly to the main DNN core repo.  

Not only is this not an accurate depiction of the DNN activity that's occurring in GitHub, but it also requires that everyone who wants that credit to only contribute to the core.  All other open-source extensions are not considered with the current point aggregation.  

This update would hope that there is a way to aggregate the points for GitHub activity to include any repo that includes the `DNNCMS` topic.  

The intent here is that everyone who contributes to any meaningful project that is maintained for the DNN community are also rewarded.  This would mean that all open-source activity is then counted, and not only the activity going into DNN Platform directly (only).

**Comment by david-poindexter** [comment]
@WillStrohl this already works the way you desire it, and even better.  It searches all repos on GitHub with a query of `dnncms` or `dotnetnuke`.  It has this query configuration for `Issues` and `Pull Requests`.  So it not only includes code contributions, but issue reports as well.  

The best way for a repo to be included is to add one or both of the topics (`dnncms` and/or `dotnetnuke`).  The `dotnetnuke` topic was an attempt to catch all the older repos that may have never added the `dnncms` topic.  I personally have reached out to tons of repo owners to request they add these topics if they don't already exist on a community repo.

I'm sure there are even more things we can explore moving forward, but this is a great start!

I'll go ahead and close this issue, but feel free to reply and I'll open if necessary.

**Comment by WillStrohl** [comment]
None of these PRs appear in my stats...  🤔 

https://github.com/DNNCommunity/Dnn.CommunityForums/pulls?q=is%3Aclosed+is%3Apr+author%3Awillstrohl+

My profile is using my username here, `WillStrohl`.  

![image](https://github.com/DNNCommunity/Dnn.CommunityMetrics/assets/938023/3e4d44a5-be4c-4f6c-a321-e1c2cba3b430)

The Community Forums doesn't have the `dotnetnuke` topic, but it does have `dnncms`.  🤔 

![image](https://github.com/DNNCommunity/Dnn.CommunityMetrics/assets/938023/b5b2e809-3e38-4c0d-bed4-bdf086324072)

**Comment by david-poindexter** [comment]
@WillStrohl this is odd indeed.  I'll re-open this issue as it is worth further investigation.  Just a thought, do you think perhaps the profile field value is case-sensitive as it relates to the GitHub API query code?  I haven't had time to dig into code, but I thought I'd share that if you want to just give that a shot for the next scheduled job run.

**Comment by WillStrohl** [comment]
Okay, just in case there is a case-sensitivity use case here, I've updated my GitHub username to be `WillStrohl`.  It was tricky though, because DNN still has that annoying `DisplayName` error message about needing to be unique.

**Comment by david-poindexter** [comment]
I'm not sure that was it, but it was worth a try.  There appears to be something weird going on because you don't have ANY GitHub-related activity showing (but you obviously should have GitHub activity).  I need to give some thought as to how to best troubleshoot this.  One way or another, we need to find a way to resolve this because who knows at this point how accurate these numbers really are at this point.  🤷🏼

**Comment by WillStrohl** [comment]
It does appear that the username is oddly case-sensitive for some reason.  ☹️  I have activity in my account today after making that change yesterday!  🤯 

![image](https://github.com/DNNCommunity/Dnn.CommunityMetrics/assets/938023/f6c5e16b-871b-4027-9997-051468f2d134)

**Comment by david-poindexter** [comment]
@WillStrohl that is fantastic news!  (Well…that you have GitHub stats now. I am assuming the username case-sensitivity lies with the GitHub API.)

I’ll go ahead and close this issue.  We’ll just need to try and remember this if others experience a similar issue in the future.

**Comment by WillStrohl** [comment]
I haven't looked at the code for this myself, especially since the recent updates.  Is there anything in their API to prevent this issue?  It's odd that a username is case-sensitive.  I mean, a lot of people use their email address for their username, which is not case sensitive by standard.  Oh well...

**Comment by david-poindexter** [comment]
I haven't looked into that, but will try to do that if nobody else gets to it before me.
