### ISSUE TITLE
Add link to pull request / issue in detail view

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityMetrics#31]
IMO it would be nice if one could click through to the actual PR / issue etc.  in the details view?
Not sure how much work that is and if it's in line with how the module stores the data though..

![image](https://github.com/DNNCommunity/Dnn.CommunityMetrics/assets/8999382/affed467-4dca-4365-ae4b-6c8473c5516f)

**Comment by WillStrohl** [comment]
It would certainly make things more transparent about where/how someone is getting credit.  That could help everyone be more informed about where/how to do this themselves.

**Comment by david-poindexter** [comment]
Nice idea!  I'm not sure of the level of effort for this, but it is worth looking into.
