### ISSUE TITLE
Page jumps top top of the page when opening a calendar

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityMetrics#32]
* I did not install the latest build so sorry if this was already fixed.
* 
Issue:

1. Visit https://dnncommunity.org/Community/Dashboard#
2. Scroll down a bit
3. Click one of the icons to open a calendar for the date filter.
4. The page jumps to the top of the page, which can be confusing :-)

**Comment by david-poindexter** [comment]
@Timo-Breumelhof I was doing some work on this module and noticed this issue in the process.  I can confirm this odd behavior and agree it should not behave like this.  I'll try to take a look into this during the next round of updates in prep for the `1.3.0` release.  Thanks for reporting it!
